// Objective-C API for talking to github.com/sah4ez/pspk/pkg/pspk Go package.
//   gobind -lang=objc github.com/sah4ez/pspk/pkg/pspk
//
// File is generated by gobind. Do not edit.

#ifndef __Pspk_H__
#define __Pspk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class PspkGetAllOptions;
@class PspkKey;
@protocol PspkPSPK;
@class PspkPSPK;

@protocol PspkPSPK <NSObject>
- (NSString* _Nonnull)downloadByLink:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)generateLink:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
// skipped method PSPK.GetAll with unsupported parameter or return types

- (NSData* _Nullable)load:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
- (BOOL)publish:(NSString* _Nullable)name key:(NSData* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
@end

@interface PspkGetAllOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull nameKey;
@property (nonatomic) NSString* _Nonnull nameRegex;
@property (nonatomic) NSString* _Nonnull output;
@property (nonatomic) NSString* _Nonnull lastKey;
@property (nonatomic) long limit;
@end

@interface PspkKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull key;
@end

FOUNDATION_EXPORT NSString* _Nonnull const PspkLastIDKEy;
FOUNDATION_EXPORT NSString* _Nonnull const PspkLimitKey;
FOUNDATION_EXPORT NSString* _Nonnull const PspkLinkKey;
FOUNDATION_EXPORT NSString* _Nonnull const PspkNameKey;
FOUNDATION_EXPORT NSString* _Nonnull const PspkNameSearchKey;
FOUNDATION_EXPORT NSString* _Nonnull const PspkOutputKey;
FOUNDATION_EXPORT NSString* _Nonnull const PspkQRCodeKey;
FOUNDATION_EXPORT NSString* _Nonnull const PspkUserAgent;

@class PspkPSPK;

@interface PspkPSPK : NSObject <goSeqRefInterface, PspkPSPK> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)downloadByLink:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)generateLink:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
// skipped method PSPK.GetAll with unsupported parameter or return types

- (NSData* _Nullable)load:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
- (BOOL)publish:(NSString* _Nullable)name key:(NSData* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
@end

#endif
