
// Objective-C API for talking to the following Go packages
//
//	github.com/l-vitaly/pspklib
//	github.com/sah4ez/pspk/pkg/pspk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pspklib_FRAMEWORK_H__
#define __Pspklib_FRAMEWORK_H__

#include "Pspklib.objc.h"
#include "Pspk.objc.h"
#include "Universe.objc.h"

#endif
